spring.application.name=shedules-management-module
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/quartz?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
spring.datasource.username=root
spring.datasource.password=root

# Spring Data JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#### Quartz ####

# 告訴 Spring Boot 使用 JDBC 儲存方式（JobStore），以資料庫儲存所有 Job、Trigger、排程等資訊
spring.quartz.job-store-type=jdbc

# 確保使用 FOR UPDATE 鎖定特定行
spring.quartz.properties.org.quartz.jobStore.selectWithLockSQL = SELECT * FROM {0}LOCKS WHERE SCHED_NAME = {1} AND LOCK_NAME = ? FOR UPDATE

# 在 Spring 啟動時會自動建立 Quartz 所需的資料表（使用預設 SQL 腳本，在開發環境使用	），生產環境設置為 never (建議手動建表)
# 可以先用 always 先建置表，再改 never
spring.quartz.jdbc.initialize-schema=always

# 設定此 Scheduler 的名稱，可用於監控、日誌識別
spring.quartz.properties.org.quartz.scheduler.instanceName=clusteredScheduler

# 讓 Quartz 自動產生唯一的 instanceId (在叢集模式下，每個節點都需要唯一的 ID)
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO

# 使用 JDBC 的 Transactional JobStore（支援 Spring 的交易控制）
#spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX

# 這是 JDBC 與特定資料庫（此處為 MySQL）互動的橋接類別
#spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate

# 在 Quartz 配置中設定（如果使用 Spring 則寫在 properties 裡）
spring.quartz.properties.org.quartz.jobStore.txIsolationLevelReadCommitted = true

# 指定所有 Quartz 表格的前綴名
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_

# 強制 Quartz 在獲取 Trigger 時先拿到鎖，避免多個節點同時獲取同一個 Trigger 導致的後續狀態衝突。
spring.quartz.properties.org.quartz.jobStore.acquireTriggersWithinLock = true

# 啟用 叢集模式，允許多節點共用同一組排程任務
spring.quartz.properties.org.quartz.jobStore.isClustered=true

# 定時會向資料庫「報到」一次，表示自己仍在線，藉此機制來偵測某個節點是否失效 (單位: 毫秒)
spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval=15000

# 設定 Quartz 是否使用屬性（String）來儲存 JobData
spring.quartz.properties.org.quartz.jobStore.useProperties=false

# 指定使用哪種執行緒類別
#spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool

# 設定 Scheduler 最多可以同時執行的 Job 數量
spring.quartz.properties.org.quartz.threadPool.threadCount=10

# 設定執行緒的優先權，5 為預設值，範圍為 1（最低）~10（最高）
spring.quartz.properties.org.quartz.threadPool.threadPriority=5




